/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dani
 */
public class Vista extends javax.swing.JFrame {
       private DefaultTableModel tabla;
       private DefaultListModel l1;
       private DefaultListModel l2;
       private DefaultListModel l3;
      
    /**
     * Creates new form Vista
     */
    public Vista() throws SQLException {
        //Añado un titulo al proyecto, saldra en la ventana
        setTitle("Proyecto Final Programación");
        //Permite que se vea la vista
        setVisible(true);
        //Nos permite que la ventana sea modificable o no
        setResizable(false);
        initComponents(); 
        //Creamos la lista de Clientes //Jlist
        l1 = new DefaultListModel();
        //Ceamos la lista de Pelicula //Jlist
        l2 = new DefaultListModel();
        //Creamos la lista de Alquiler //Jlist
        l3 = new DefaultListModel();
        //Crea la tabla de Alquiler //Jtable
        tabla = new DefaultTableModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelCLIENTE = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLIDOS = new javax.swing.JLabel();
        jLabel5EDAD = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDOS = new javax.swing.JTextField();
        jTextFieldEDAD = new javax.swing.JTextField();
        jLabelPELICULA = new javax.swing.JLabel();
        jLabelCODIGO = new javax.swing.JLabel();
        jLabelTITULO = new javax.swing.JLabel();
        jLabelAUTOR = new javax.swing.JLabel();
        jLabelANIO = new javax.swing.JLabel();
        jLabeGENERO = new javax.swing.JLabel();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jTextFieldTITULO = new javax.swing.JTextField();
        jTextFieldDIRECTOR = new javax.swing.JTextField();
        jTextFielANIO = new javax.swing.JTextField();
        jTextFieldGENERO = new javax.swing.JTextField();
        jLabelALQUILER = new javax.swing.JLabel();
        jLabelFECHAALQUILADA = new javax.swing.JLabel();
        jTextFieldFECHAALQUILADA = new javax.swing.JTextField();
        jLabelFECHADEVOLUCION = new javax.swing.JLabel();
        jTextFieldFECHADEVOLUCION = new javax.swing.JTextField();
        jLabelDNICLIENTE = new javax.swing.JLabel();
        jTextFieldDNICLIENTE = new javax.swing.JTextField();
        jLabelCODPELICULA = new javax.swing.JLabel();
        jTextFieldCODPELICULA = new javax.swing.JTextField();
        jButtonBORRAR = new javax.swing.JButton();
        jButtonANADIR = new javax.swing.JButton();
        jButtonLIMPIAR = new javax.swing.JButton();
        jScrollPaneLISTA = new javax.swing.JScrollPane();
        jTextArea1CAJA = new javax.swing.JTextArea();
        jButtonACTIVARALQUILER = new javax.swing.JButton();
        jTextFieldCreditos1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBorrarT = new javax.swing.JButton();
        jLabelFecha_AlquiladaT = new javax.swing.JLabel();
        jLabelFecha_DevueltaT = new javax.swing.JLabel();
        jTextFieldFecha_AlquiladaT = new javax.swing.JTextField();
        jTextFieldFecha_DevueltaT = new javax.swing.JTextField();
        jLabelDniClienteT = new javax.swing.JLabel();
        jLabelCodPeliculaT = new javax.swing.JLabel();
        jTextFieldDniClienteT = new javax.swing.JTextField();
        jTextFieldCodPeliculaT = new javax.swing.JTextField();
        jTextFieldCreditos2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTituloT = new javax.swing.JTextField();
        jTextFieldApellidosT = new javax.swing.JTextField();
        jTextFieldNombreT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jLabel1ClientesOpcional = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPeliculas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAlquileres = new javax.swing.JList<>();
        jLabel2PeliculasOpcional = new javax.swing.JLabel();
        jLabel3AlquileresOpcional = new javax.swing.JLabel();
        jButtonVolcarAlquileres = new javax.swing.JButton();
        jButtonActualizarL = new javax.swing.JButton();
        jTextFieldCreditos3 = new javax.swing.JTextField();
        jButtonBorrarClienteLista = new javax.swing.JButton();
        jButtonBorrarPeliculaLista = new javax.swing.JButton();
        jTextFieldNOMBRELISTA = new javax.swing.JTextField();
        jTextFieldTITULOLISTA = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemActivarCreditos = new javax.swing.JMenuItem();
        jMenuItem1DesactivarCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelCLIENTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCLIENTE.setText("Cliente");

        jLabelDNI.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNI.setText("Dni");

        jLabelNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelNOMBRE.setText("Nombre");

        jLabelAPELLIDOS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAPELLIDOS.setText("Apellidos");

        jLabel5EDAD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5EDAD.setText("Edad");

        jLabelPELICULA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPELICULA.setText("Pelicula");

        jLabelCODIGO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODIGO.setText("Codigo");

        jLabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelTITULO.setText("Titulo");

        jLabelAUTOR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAUTOR.setText("Director");

        jLabelANIO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelANIO.setText("Año");

        jLabeGENERO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabeGENERO.setText("Genero");

        jLabelALQUILER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelALQUILER.setText("Alquiler");

        jLabelFECHAALQUILADA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHAALQUILADA.setText("Fecha alquilada");

        jTextFieldFECHAALQUILADA.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelFECHADEVOLUCION.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHADEVOLUCION.setText("Fecha devolucion");

        jTextFieldFECHADEVOLUCION.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelDNICLIENTE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNICLIENTE.setText("DniCliente");

        jTextFieldDNICLIENTE.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDNICLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNICLIENTEActionPerformed(evt);
            }
        });

        jLabelCODPELICULA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODPELICULA.setText("CodPelicula");

        jTextFieldCODPELICULA.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButtonBORRAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBORRAR.setText("Borrar");
        jButtonBORRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBORRARMouseClicked(evt);
            }
        });

        jButtonANADIR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonANADIR.setText("Añadir");
        jButtonANADIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonANADIRMouseClicked(evt);
            }
        });
        jButtonANADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANADIRActionPerformed(evt);
            }
        });

        jButtonLIMPIAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLIMPIAR.setText("Limpiar");
        jButtonLIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLIMPIARMouseClicked(evt);
            }
        });

        jTextArea1CAJA.setEditable(false);
        jTextArea1CAJA.setColumns(20);
        jTextArea1CAJA.setRows(5);
        jScrollPaneLISTA.setViewportView(jTextArea1CAJA);

        jButtonACTIVARALQUILER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonACTIVARALQUILER.setText("Activar");
        jButtonACTIVARALQUILER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonACTIVARALQUILERMouseClicked(evt);
            }
        });

        jTextFieldCreditos1.setEditable(false);
        jTextFieldCreditos1.setBackground(new java.awt.Color(245, 255, 239));
        jTextFieldCreditos1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextFieldCreditos1.setText("DANIEL SIERRA RÁEZ ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAPELLIDOS)
                                    .addComponent(jLabel5EDAD)
                                    .addComponent(jLabelNOMBRE)
                                    .addComponent(jLabelDNI)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCODIGO)
                                    .addComponent(jLabelANIO)
                                    .addComponent(jLabelAUTOR)
                                    .addComponent(jLabelTITULO)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabeGENERO)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDIRECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelFECHAALQUILADA)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonACTIVARALQUILER)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelFECHADEVOLUCION)
                                                .addComponent(jLabelDNICLIENTE)
                                                .addComponent(jLabelCODPELICULA))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldFECHADEVOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 122, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelALQUILER)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonANADIR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonBORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonLIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPELICULA)
                .addGap(244, 673, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCLIENTE)
                    .addComponent(jLabelALQUILER))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFECHAALQUILADA)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDNI)
                        .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFECHADEVOLUCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNOMBRE)
                        .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFECHADEVOLUCION)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDNICLIENTE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAPELLIDOS)
                        .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5EDAD)
                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCODPELICULA)
                    .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonACTIVARALQUILER)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonANADIR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCODIGO)
                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBORRAR)
                    .addComponent(jButtonLIMPIAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTITULO)
                            .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAUTOR)
                            .addComponent(jTextFieldDIRECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelANIO)
                            .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeGENERO)
                            .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 78, Short.MAX_VALUE)
                .addComponent(jTextFieldCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonBorrarT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBorrarT.setText("Borrar ");
        jButtonBorrarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarTMouseClicked(evt);
            }
        });

        jLabelFecha_AlquiladaT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFecha_AlquiladaT.setText("Fecha Alquilada");

        jLabelFecha_DevueltaT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFecha_DevueltaT.setText("Fecha Devuelta");

        jTextFieldFecha_AlquiladaT.setEditable(false);
        jTextFieldFecha_AlquiladaT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldFecha_AlquiladaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFecha_AlquiladaTActionPerformed(evt);
            }
        });

        jTextFieldFecha_DevueltaT.setEditable(false);
        jTextFieldFecha_DevueltaT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelDniClienteT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDniClienteT.setText("DniCliente");

        jLabelCodPeliculaT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCodPeliculaT.setText("CodPelicula");

        jTextFieldDniClienteT.setEditable(false);
        jTextFieldDniClienteT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDniClienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniClienteTActionPerformed(evt);
            }
        });

        jTextFieldCodPeliculaT.setEditable(false);
        jTextFieldCodPeliculaT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextFieldCreditos2.setEditable(false);
        jTextFieldCreditos2.setBackground(new java.awt.Color(245, 255, 239));
        jTextFieldCreditos2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextFieldCreditos2.setText("DANIEL SIERRA RÁEZ ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Titulo");

        jTextFieldTituloT.setEditable(false);
        jTextFieldTituloT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTituloT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloTActionPerformed(evt);
            }
        });

        jTextFieldApellidosT.setEditable(false);
        jTextFieldApellidosT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextFieldNombreT.setEditable(false);
        jTextFieldNombreT.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Borrar Alquiler");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabelDniClienteT)
                            .addComponent(jLabelCodPeliculaT)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldDniClienteT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodPeliculaT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTituloT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldApellidosT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelFecha_AlquiladaT)
                                            .addComponent(jLabelFecha_DevueltaT))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldFecha_AlquiladaT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldFecha_DevueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 73, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jButtonBorrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(97, 97, 97))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(85, 85, 85))
                                            .addComponent(jTextFieldCreditos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha_AlquiladaT)
                    .addComponent(jTextFieldFecha_AlquiladaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDniClienteT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDniClienteT))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFecha_DevueltaT)
                    .addComponent(jTextFieldFecha_DevueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldApellidosT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodPeliculaT)
                            .addComponent(jTextFieldCodPeliculaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBorrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTituloT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCreditos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Alquiler", jPanel3);

        jListClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListClientes);

        jLabel1ClientesOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1ClientesOpcional.setText("Clientes");

        jListPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPeliculasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListPeliculas);

        jScrollPane4.setViewportView(jListAlquileres);

        jLabel2PeliculasOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2PeliculasOpcional.setText("Peliculas");

        jLabel3AlquileresOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3AlquileresOpcional.setText("Alquileres");

        jButtonVolcarAlquileres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVolcarAlquileres.setText("Volcar");
        jButtonVolcarAlquileres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolcarAlquileresMouseClicked(evt);
            }
        });

        jButtonActualizarL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonActualizarL.setText("Actualizar");
        jButtonActualizarL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonActualizarLMouseClicked(evt);
            }
        });

        jTextFieldCreditos3.setEditable(false);
        jTextFieldCreditos3.setBackground(new java.awt.Color(245, 255, 239));
        jTextFieldCreditos3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextFieldCreditos3.setText("DANIEL SIERRA RÁEZ ");
        jTextFieldCreditos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditos3ActionPerformed(evt);
            }
        });

        jButtonBorrarClienteLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBorrarClienteLista.setText("Borrar Cliente");
        jButtonBorrarClienteLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarClienteListaMouseClicked(evt);
            }
        });
        jButtonBorrarClienteLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarClienteListaActionPerformed(evt);
            }
        });

        jButtonBorrarPeliculaLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBorrarPeliculaLista.setText("Borrar Pelicula");
        jButtonBorrarPeliculaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarPeliculaListaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1ClientesOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jLabel2PeliculasOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3AlquileresOpcional)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCreditos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jTextFieldNOMBRELISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonBorrarClienteLista)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarPeliculaLista)
                    .addComponent(jTextFieldTITULOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizarL)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVolcarAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1ClientesOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2PeliculasOpcional)
                    .addComponent(jLabel3AlquileresOpcional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolcarAlquileres)
                    .addComponent(jButtonActualizarL)
                    .addComponent(jButtonBorrarClienteLista)
                    .addComponent(jButtonBorrarPeliculaLista))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNOMBRELISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTITULOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCreditos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listas", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemActivarCreditos.setText("ON Creditos");
        jMenuItemActivarCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemActivarCreditosMouseClicked(evt);
            }
        });
        jMenu3.add(jMenuItemActivarCreditos);

        jMenuItem1DesactivarCreditos.setText("OFF Creditos");
        jMenuItem1DesactivarCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1DesactivarCreditosMouseClicked(evt);
            }
        });
        jMenu3.add(jMenuItem1DesactivarCreditos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNICLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNICLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNICLIENTEActionPerformed

    private void jButtonANADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANADIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonANADIRActionPerformed

    private void jButtonANADIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonANADIRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonANADIRMouseClicked
    
    //Getter y setter necesarios para utilizar la vista
    public DefaultListModel getL1() {
        return l1;
    }

    public DefaultListModel getL2() {
        return l2;
    }

    public DefaultListModel getL3() {
        return l3;
    }
    
    public JList<String> getjListAlquileres() {
        return jListAlquileres;
    }

    public JList<String> getjListClientes() {
        return jListClientes;
    }

    public JList<String> getjListPeliculas() {
        return jListPeliculas;
    }
    
    public DefaultTableModel getTabla() {
        return tabla;
    }

    public JTable getjTable(){
        return jTable1;
    }

    public JButton getjButtonANADIR() {
        return jButtonANADIR;
    }

    public JButton getjButtonBorrarT() {
        return jButtonBorrarT;
    }
    
    public JButton getjButtonVolcarAlquileres() {
        return jButtonVolcarAlquileres;
    }
    
    public JButton getjButtonBORRAR() {
        return jButtonBORRAR;
    }

    public JButton getjButtonActualizarL() {
        return jButtonActualizarL;
    }
    
    public JButton getjButtonACTIVARALQUILER() {
        return jButtonACTIVARALQUILER;
    }

    public JMenuItem getjMenuItem1DesactivarCreditos() {
        return jMenuItem1DesactivarCreditos;
    }

    public JButton getjButtonLIMPIAR() {
        return jButtonLIMPIAR;
    }

    public JMenuItem getjMenuItemActivarCreditos() {
        return jMenuItemActivarCreditos;
    }

    public void setjMenuItemCreditos(JMenuItem jMenuItemCreditos) {
        this.jMenuItemActivarCreditos = jMenuItemCreditos;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }
    
    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }
   
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPaneLISTA() {
        return jScrollPaneLISTA;
    }

    public void setjScrollPaneLISTA(JScrollPane jScrollPaneLISTA) {
        this.jScrollPaneLISTA = jScrollPaneLISTA;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextArea getjTextArea1CAJA() {
        return jTextArea1CAJA;
    }

    public void setjTextArea1CAJA(JTextArea jTextArea1CAJA) {
        this.jTextArea1CAJA = jTextArea1CAJA;
    }

    public JTextField getjTextFielANIO() {
        return jTextFielANIO;
    }

    public void setjTextFielANIO(JTextField jTextFielANIO) {
        this.jTextFielANIO = jTextFielANIO;
    }

    public JTextField getjTextFieldAPELLIDOS() {
        return jTextFieldAPELLIDOS;
    }

    public void setjTextFieldAPELLIDOS(JTextField jTextFieldAPELLIDOS) {
        this.jTextFieldAPELLIDOS = jTextFieldAPELLIDOS;
    }

    public JTextField getjTextFieldCODIGO() {
        return jTextFieldCODIGO;
    }

    public JLabel getjLabelCodPeliculaT() {
        return jLabelCodPeliculaT;
    }

    public JLabel getjLabelDniClienteT() {
        return jLabelDniClienteT;
    }
    
    public void setjTextFieldCODIGO(JTextField jTextFieldCODIGO) {
        this.jTextFieldCODIGO = jTextFieldCODIGO;
    }

    public JTextField getjTextFieldCODPELICULA() {
        return jTextFieldCODPELICULA;
    }

    public void setjTextFieldCODPELICULA(JTextField jTextFieldCODPELICULA) {
        this.jTextFieldCODPELICULA = jTextFieldCODPELICULA;
    }

    public JTextField getjTextFieldDIRECTOR() {
        return jTextFieldDIRECTOR;
    }

    public void setjTextFieldDIRECTOR(JTextField jTextFieldDIRECTOR) {
        this.jTextFieldDIRECTOR = jTextFieldDIRECTOR;
    }

    public JTextField getjTextFieldDNI() {
        return jTextFieldDNI;
    }

    public void setjTextFieldDNI(JTextField jTextFieldDNI) {
        this.jTextFieldDNI = jTextFieldDNI;
    }

    public JTextField getjTextFieldDNICLIENTE() {
        return jTextFieldDNICLIENTE;
    }

    public void setjTextFieldDNICLIENTE(JTextField jTextFieldDNICLIENTE) {
        this.jTextFieldDNICLIENTE = jTextFieldDNICLIENTE;
    }

    public JTextField getjTextFieldEDAD() {
        return jTextFieldEDAD;
    }

    public void setjTextFieldEDAD(JTextField jTextFieldEDAD) {
        this.jTextFieldEDAD = jTextFieldEDAD;
    }

    public JTextField getjTextFieldFECHAALQUILADA() {
        return jTextFieldFECHAALQUILADA;
    }

    public void setjTextFieldFECHAALQUILADA(JTextField jTextFieldFECHAALQUILADA) {
        this.jTextFieldFECHAALQUILADA = jTextFieldFECHAALQUILADA;
    }

    public JTextField getjTextFieldCreditos2() {
        return jTextFieldCreditos2;
    }

    public JTextField getjTextFieldCreditos3() {
        return jTextFieldCreditos3;
    }

    public JTextField getjTextFieldCreditos1() {
        return jTextFieldCreditos1;
    }

    public JTextField getjTextFieldFECHADEVOLUCION() {
        return jTextFieldFECHADEVOLUCION;
    }

    public void setjTextFieldFECHADEVOLUCION(JTextField jTextFieldFECHADEVOLUCION) {
        this.jTextFieldFECHADEVOLUCION = jTextFieldFECHADEVOLUCION;
    }

    public JTextField getjTextFieldGENERO() {
        return jTextFieldGENERO;
    }

    public void setjTextFieldGENERO(JTextField jTextFieldGENERO) {
        this.jTextFieldGENERO = jTextFieldGENERO;
    }

    public JTextField getjTextFieldCodPeliculaT() {
        return jTextFieldCodPeliculaT;
    }

    public JTextField getjTextFieldDniClienteT() {
        return jTextFieldDniClienteT;
    }

    public JTextField getjTextFieldNombreClienteT() {
        return jTextFieldFecha_AlquiladaT;
    }

    public JTextField getjTextFieldNombrePeliculaT() {
        return jTextFieldFecha_DevueltaT;
    }
    
    public JTextField getjTextFieldNOMBRE() {
        return jTextFieldNOMBRE;
    }

    public JTextField getjTextFieldFecha_AlquiladaT() {
        return jTextFieldFecha_AlquiladaT;
    }

    public JTextField getjTextFieldFecha_DevueltaT() {
        return jTextFieldFecha_DevueltaT;
    }

    public void setjTextFieldNOMBRE(JTextField jTextFieldNOMBRE) {
        this.jTextFieldNOMBRE = jTextFieldNOMBRE;
    }

    public JTextField getjTextFieldTITULO() {
        return jTextFieldTITULO;
    }

    public void setjTextFieldTITULO(JTextField jTextFieldTITULO) {
        this.jTextFieldTITULO = jTextFieldTITULO;
    }

    public JButton getjButtonBorrarClienteLista() {
        return jButtonBorrarClienteLista;
    }

    public JButton getjButtonBorrarPeliculaLista() {
        return jButtonBorrarPeliculaLista;
    }

    public JTextField getjTextFieldNOMBRELISTA() {
        return jTextFieldNOMBRELISTA;
    }

    public JTextField getjTextFieldTITULOLISTA() {
        return jTextFieldTITULOLISTA;
    }

    public JTextField getjTextFieldApellidosT() {
        return jTextFieldApellidosT;
    }

    public JTextField getjTextFieldNombreT() {
        return jTextFieldNombreT;
    }

    public JTextField getjTextFieldTituloT() {
        return jTextFieldTituloT;
    }

    private void jButtonLIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLIMPIARMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jButtonLIMPIARMouseClicked

    private void jButtonACTIVARALQUILERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonACTIVARALQUILERMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTIVARALQUILERMouseClicked

    private void jTextFieldFecha_AlquiladaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFecha_AlquiladaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFecha_AlquiladaTActionPerformed

    private void jButtonBORRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBORRARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBORRARMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow(); 

        jTextFieldDniClienteT.setText(jTable1.getValueAt(fila,0).toString());
        jTextFieldNombreT.setText(jTable1.getValueAt(fila,1).toString());
        jTextFieldApellidosT.setText(jTable1.getValueAt(fila,2).toString());
        jTextFieldCodPeliculaT.setText(jTable1.getValueAt(fila,3).toString());
        jTextFieldTituloT.setText(jTable1.getValueAt(fila,4).toString());
        jTextFieldFecha_AlquiladaT.setText(jTable1.getValueAt(fila,5).toString());
        jTextFieldFecha_DevueltaT.setText(jTable1.getValueAt(fila,6).toString());
        jTextFieldDniClienteT.setEnabled(false);
        jTextFieldNombreT.setEnabled(false);
        jTextFieldApellidosT.setEnabled(false);
        jTextFieldCodPeliculaT.setEnabled(false);
        jTextFieldTituloT.setEnabled(false);
        jTextFieldFecha_AlquiladaT.setEnabled(false);
        jTextFieldFecha_DevueltaT.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItemActivarCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemActivarCreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActivarCreditosMouseClicked

    private void jMenuItem1DesactivarCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1DesactivarCreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1DesactivarCreditosMouseClicked

    private void jButtonBorrarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarTMouseClicked

    private void jTextFieldCreditos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditos3ActionPerformed

    private void jButtonActualizarLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonActualizarLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarLMouseClicked

    private void jButtonVolcarAlquileresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolcarAlquileresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolcarAlquileresMouseClicked

    private void jTextFieldDniClienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniClienteTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniClienteTActionPerformed

    private void jListClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClientesMouseClicked
     int fila = jListClientes.getSelectedIndex();  
     jTextFieldNOMBRELISTA.setText(l1.getElementAt(fila).toString());
    }//GEN-LAST:event_jListClientesMouseClicked

    private void jButtonBorrarClienteListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarClienteListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarClienteListaActionPerformed

    private void jButtonBorrarClienteListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarClienteListaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarClienteListaMouseClicked

    private void jButtonBorrarPeliculaListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarPeliculaListaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarPeliculaListaMouseClicked

    private void jListPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPeliculasMouseClicked
        // TODO add your handling code here:
     int fila = jListPeliculas.getSelectedIndex();  
     jTextFieldTITULOLISTA.setText(l2.getElementAt(fila).toString());
    }//GEN-LAST:event_jListPeliculasMouseClicked

    private void jTextFieldTituloTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonACTIVARALQUILER;
    private javax.swing.JButton jButtonANADIR;
    private javax.swing.JButton jButtonActualizarL;
    private javax.swing.JButton jButtonBORRAR;
    private javax.swing.JButton jButtonBorrarClienteLista;
    private javax.swing.JButton jButtonBorrarPeliculaLista;
    private javax.swing.JButton jButtonBorrarT;
    private javax.swing.JButton jButtonLIMPIAR;
    private javax.swing.JButton jButtonVolcarAlquileres;
    private javax.swing.JLabel jLabeGENERO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1ClientesOpcional;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2PeliculasOpcional;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3AlquileresOpcional;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5EDAD;
    private javax.swing.JLabel jLabelALQUILER;
    private javax.swing.JLabel jLabelANIO;
    private javax.swing.JLabel jLabelAPELLIDOS;
    private javax.swing.JLabel jLabelAUTOR;
    private javax.swing.JLabel jLabelCLIENTE;
    private javax.swing.JLabel jLabelCODIGO;
    private javax.swing.JLabel jLabelCODPELICULA;
    private javax.swing.JLabel jLabelCodPeliculaT;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNICLIENTE;
    private javax.swing.JLabel jLabelDniClienteT;
    private javax.swing.JLabel jLabelFECHAALQUILADA;
    private javax.swing.JLabel jLabelFECHADEVOLUCION;
    private javax.swing.JLabel jLabelFecha_AlquiladaT;
    private javax.swing.JLabel jLabelFecha_DevueltaT;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelPELICULA;
    private javax.swing.JLabel jLabelTITULO;
    private javax.swing.JList<String> jListAlquileres;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListPeliculas;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1DesactivarCreditos;
    private javax.swing.JMenuItem jMenuItemActivarCreditos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPaneLISTA;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1CAJA;
    private javax.swing.JTextField jTextFielANIO;
    private javax.swing.JTextField jTextFieldAPELLIDOS;
    private javax.swing.JTextField jTextFieldApellidosT;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldCODPELICULA;
    private javax.swing.JTextField jTextFieldCodPeliculaT;
    private javax.swing.JTextField jTextFieldCreditos1;
    private javax.swing.JTextField jTextFieldCreditos2;
    private javax.swing.JTextField jTextFieldCreditos3;
    private javax.swing.JTextField jTextFieldDIRECTOR;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNICLIENTE;
    private javax.swing.JTextField jTextFieldDniClienteT;
    private javax.swing.JTextField jTextFieldEDAD;
    private javax.swing.JTextField jTextFieldFECHAALQUILADA;
    private javax.swing.JTextField jTextFieldFECHADEVOLUCION;
    private javax.swing.JTextField jTextFieldFecha_AlquiladaT;
    private javax.swing.JTextField jTextFieldFecha_DevueltaT;
    private javax.swing.JTextField jTextFieldGENERO;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldNOMBRELISTA;
    private javax.swing.JTextField jTextFieldNombreT;
    private javax.swing.JTextField jTextFieldTITULO;
    private javax.swing.JTextField jTextFieldTITULOLISTA;
    private javax.swing.JTextField jTextFieldTituloT;
    // End of variables declaration//GEN-END:variables

}
